# vim: ft=yaml

- name: thugcraft minecraft server provisioning
  hosts: all
  become: true
  gather_facts: no
  pre_tasks:
  - name: 'install python2'
    raw: sudo apt-get -y install python-simplejson

  tasks:
  - name: add users
    user:
      name: '{{ item }}'
      group: sudo
      shell: /bin/bash
    with_items:
      - heidar
      - dabb

  - name: add ssh public keys
    authorized_key:
      user: '{{ item }}'
      state: present
      key: https://github.com/{{ 'item' }}.keys
    with_items:
      - dabb
      - heidar

  - name: add oracle java apt repository
    apt_repository:
      repo: ppa:webupd8team/java
      state: present

  - name: accept java 8 License
    become: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: install packages
    apt:
      name: '{{ item }}'
      state: present
      update_cache: yes
    with_items:
      - htop
      - iotop
      - munin
      - munin-node
      - nginx
      - git
      - perl
      - libjson-perl
      - python
      - make
      - wget
      - rdiff-backup
      - rsync
      - socat
      - iptables
      - vim
      - certbot
      - software-properties-common
      - oracle-java8-installer
      - oracle-java8-set-default

  - name: deny incoming traffic
    ufw:
      direction: incoming
      policy: deny

  - name: allow outgoing traffic
    ufw:
      direction: outgoing
      policy: allow

  - name: allow services
    ufw:
      rule: allow
      port: '{{ item }}'
    with_items:
      - ssh
      - http
      - https
      - 25565

  - name: enable ufw
    ufw:
      state: enabled

  - name: create website directory
    file: path=/var/www/thugcraft.club/public_html state=directory

  - name: copy website over
    git:
      repo: https://github.com/heidar/thugcraft-website.git
      dest: /var/www/thugcraft.club/public_html

  - name: download mscs release
    git:
      repo: https://github.com/MinecraftServerControl/mscs.git
      dest: /root/mscs
      version: v.16.06.00

  - name: check if mscs is installed
    stat:
      path: /opt/mscs
    register: mscs

  - name: install mscs
    make:
      chdir: /root/mscs
      target: install
    when: not mscs.stat.exists

  - name: copy nginx config
    copy:
      src: thugcraft.club.nginx.conf
      dest: /etc/nginx/sites-enabled/thugcraft.club

  - name: create letsencrypt certificates
    command: certbot certonly --standalone -m yo@thugcraft.club --agree-tos --non-interactive -d thugcraft.club -d www.thugcraft.club '{{ letsencrypt_environment }}'
    args:
      creates: /etc/letsencrypt/live/thugcraft.club/privkey.pem

  - name: restart nginx
    service:
      name: nginx
      state: restarted
